M48
; DRILL file KiCad 10.0.6 date 2026-09-28T01:38:24
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T01:38:24-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X75.13Y-87.25
X75.13Y-89.25
X75.13Y-91.25
X75.13Y-93.25
X75.13Y-95.25
T2
X65.37Y-86.37
X70.37Y-86.37
M30
