M48
; DRILL file {KiCad 9.0.7} date 2026-03-15T14:46:32-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-15T14:46:32-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X77.53Y-60.575
X77.53Y-65.425
T2
X74.5Y-60.275
X74.5Y-65.725
M30
